# This rule is not used by the project keycloak-opereator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the openid.keycloak-operator.webhippie.de.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: openid-clientscope-editor-role
rules:
- apiGroups:
  - openid.keycloak-operator.webhippie.de
  resources:
  - clientscopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openid.keycloak-operator.webhippie.de
  resources:
  - clientscopes/status
  verbs:
  - get
