# This rule is not used by the project keycloak-opereator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over openid.keycloak-operator.webhippie.de.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: openid-clientscope-admin-role
rules:
- apiGroups:
  - openid.keycloak-operator.webhippie.de
  resources:
  - clientscopes
  verbs:
  - '*'
- apiGroups:
  - openid.keycloak-operator.webhippie.de
  resources:
  - clientscopes/status
  verbs:
  - get
