apiVersion: openid.keycloak-operator.webhippie.de/v1alpha1
kind: UserAttributeProtocolMapper
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: userattributeprotocolmapper-sample
spec:
  # TODO(user): Add fields here
