apiVersion: keycloak-operator.webhippie.de/v1alpha1
kind: Keycloak
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-sample
  namespace: keycloak-operator-system
spec:
  url: https://keycloak.example.com
  username:
    name: keycloak-admin
    key: username
  password:
    name: keycloak-admin
    key: password
