apiVersion: keycloak-operator.webhippie.de/v1alpha1
kind: ClusterKeycloak
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: clusterkeycloak-sample
spec:
  # TODO(user): Add fields here
