apiVersion: keycloak-operator.webhippie.de/v1alpha1
kind: Keycloak
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-sample
spec:
  # TODO(user): Add fields here
