apiVersion: keycloak-operator.webhippie.de/v1alpha1
kind: ClusterKeycloak
metadata:
  labels:
    app.kubernetes.io/name: keycloak-opereator
    app.kubernetes.io/managed-by: kustomize
  name: clusterkeycloak-sample
spec:
  url: https://keycloak.example.com
  username:
    name: keycloak-admin
    key: username
    namespace: keycloak-operator-system
  password:
    name: keycloak-admin
    key: password
    namespace: keycloak-operator-system
