# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/keycloak-operator.webhippie.de_clusterkeycloaks.yaml
- bases/keycloak-operator.webhippie.de_keycloaks.yaml
- bases/keycloak-operator.webhippie.de_clusterrealms.yaml
- bases/keycloak-operator.webhippie.de_realms.yaml
- bases/keycloak-operator.webhippie.de_users.yaml
- bases/keycloak-operator.webhippie.de_groups.yaml
- bases/identity.keycloak-operator.webhippie.de_oidcidentityproviders.yaml
- bases/identity.keycloak-operator.webhippie.de_attributeimportermappers.yaml
- bases/identity.keycloak-operator.webhippie.de_oidcadvancedgroupmappers.yaml
- bases/identity.keycloak-operator.webhippie.de_hardcodedrolemappers.yaml
- bases/openid.keycloak-operator.webhippie.de_openidclients.yaml
- bases/openid.keycloak-operator.webhippie.de_defaultscopes.yaml
- bases/openid.keycloak-operator.webhippie.de_clientscopes.yaml
- bases/openid.keycloak-operator.webhippie.de_groupmembershipprotocolmappers.yaml
- bases/openid.keycloak-operator.webhippie.de_userpropertyprotocolmappers.yaml
- bases/openid.keycloak-operator.webhippie.de_userattributeprotocolmappers.yaml
- bases/openid.keycloak-operator.webhippie.de_fullnameprotocolmappers.yaml
- bases/openid.keycloak-operator.webhippie.de_audienceprotocolmappers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
