---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: clusterkeycloaks.keycloak-operator.webhippie.de
spec:
  group: keycloak-operator.webhippie.de
  names:
    kind: ClusterKeycloak
    listKind: ClusterKeycloakList
    plural: clusterkeycloaks
    singular: clusterkeycloak
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Connected to Keycloak
      jsonPath: .status.connected
      name: Connected
      type: boolean
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterKeycloak is the Schema for the clusterkeycloaks API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of ClusterKeycloak
            properties:
              caCert:
                description: |-
                  caCert defines the root certificate authority that API clients use when
                  verifying server certificates.
                properties:
                  configMapKeyRef:
                    description: Selects a key of a ConfigMap.
                    properties:
                      key:
                        description: The key to select.
                        type: string
                      name:
                        default: ""
                        description: |-
                          Name of the referent.
                          This field is effectively required, but due to backwards compatibility is
                          allowed to be empty. Instances of this type with an empty value here are
                          almost certainly wrong.
                          More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        type: string
                      namespace:
                        description: Namespace of the ConfigMap.
                        type: string
                    required:
                    - key
                    type: object
                    x-kubernetes-map-type: atomic
                  secretKeyRef:
                    description: Selects a key of a secret.
                    properties:
                      key:
                        description: The key of the secret to select from.
                        type: string
                      name:
                        default: ""
                        description: |-
                          Name of the referent.
                          This field is effectively required, but due to backwards compatibility is
                          allowed to be empty. Instances of this type with an empty value here are
                          almost certainly wrong.
                          More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        type: string
                      namespace:
                        description: Namespace of the ConfigMap.
                        type: string
                    required:
                    - key
                    type: object
                    x-kubernetes-map-type: atomic
                type: object
              insecureSkipVerify:
                description: |-
                  insecureSkipVerify controls whether API client verifies the servers
                  certificate chain and hostname. If insecureSkipVerify is true, API client
                  accepts any certificate presented by the server and any hostname in that
                  certificate.
                type: boolean
              password:
                description: password references a secret or direct value which contains
                  admin password.
                properties:
                  key:
                    description: The key of the secret to select from.
                    type: string
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                  namespace:
                    description: Namespace of the ConfigMap.
                    type: string
                  value:
                    description: Directly specifies a value.
                    type: string
                required:
                - key
                type: object
                x-kubernetes-map-type: atomic
              realmName:
                default: master
                description: |-
                  realmName defines the realm name to authenticate the admin credentials,
                  normally this should be the master realm.
                type: string
              url:
                description: url of keycloak instance.
                type: string
              username:
                description: username references a secret or direct value which contains
                  admin username.
                properties:
                  key:
                    description: The key of the secret to select from.
                    type: string
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                  namespace:
                    description: Namespace of the ConfigMap.
                    type: string
                  value:
                    description: Directly specifies a value.
                    type: string
                required:
                - key
                type: object
                x-kubernetes-map-type: atomic
            required:
            - password
            - url
            - username
            type: object
          status:
            default:
              connected: false
            description: status defines the observed state of ClusterKeycloak
            properties:
              connected:
                description: connected shows if the Keycloak instance is connected
                  successfully.
                type: boolean
            required:
            - connected
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
